baseURL = "https://bethtian.github.io/"
languageCode = "en-us"
title = "Beth Tian"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  author = "Beth Tian"
  description = "Personal academic website and blog"
  defaultTheme = "auto"   # light / dark / auto
  ShowReadingTime = true
  ShowShareButtons = false

[params.profileMode]
enabled = true
title = "Wenjia (Beth) Tian"
subtitle = "Master Student · Risk Engineering · Duke University"
imageUrl = "/images/profilepic.jpeg"
imageTitle = "Wenjia (Beth) Tian"
imageWidth = 160
imageHeight = 160


# Top menu
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 3
